# the test of "delegated" or "cached" volume modes:

version: '3.7'
services:
  web:
    image: phusion/baseimage:0.9.19
    volumes:
      - ./src/www:/var/www:delegated
    command: /bin/bash -c "time dd if=/dev/zero of=/tmp/test.dat bs=1024 count=10000 && time dd if=/dev/zero of=/var/www/test.dat bs=1024 count=10000 && rm -rf /var/www/test.dat"
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8


